//! Supplementary multi-chunk NCF-3 conformance fixture
//! (`tests/vectors/ncf3-multichunk.json`).
//!
//! The frozen `ncf3.json` carries full `stream_hex` only for single-chunk streams — its
//! 3-chunk vector is 9 MiB and therefore digest-only. The JS conformance harnesses
//! (nmts/deploy/{wasm,worker}-conformance.mjs) need real committed MULTI-chunk bytes to
//! exercise sequential buffering and random-access chunk decryption, so this file
//! generates and guards a small supplementary fixture: `chunk_size_log2 = 10` (1 KiB
//! chunks), `plaintext_len = 2560` ⇒ 3 chunks of 1024/1024/512 bytes.
//!
//! Small chunk sizes are legal for DECODERS per CRYPTO-FORMAT §3.1 (only encoders MUST
//! write 22); the vectors-only `with_fixed` constructor produces such streams exactly as
//! the frozen `reordered_chunks` negative vector does (log2 = 6). `ncf3.json` itself is
//! FROZEN and untouched by this file.
//!
//! The tiny deterministic inputs (DEK, nonce prefix, plaintext pattern) intentionally
//! mirror `tests/vectors.rs`; the helpers are duplicated because Rust integration tests
//! are separate crates and those helpers are private there.
//!
//! * Regenerate (writes the JSON):
//!   `cargo test --features vectors gen_multichunk_fixture -- --ignored --nocapture`
//! * Verify (default under `--features vectors`): `multichunk_fixture_reproducible`
//!   rebuilds the JSON in memory and asserts byte equality with the committed file — the
//!   reproducibility guard; `multichunk_fixture_decrypts` proves the committed bytes
//!   decrypt correctly both sequentially and via random access.
#![cfg(feature = "vectors")]

use nmts_crypto::framing::{
    decrypt_chunk, Header, PartPlacement, StreamDecryptor, StreamEncryptor, HEADER_LEN,
};
use serde_json::json;
use sha2::{Digest, Sha256};
use std::path::PathBuf;

/// 1 KiB chunks — decoder-legal (CRYPTO-FORMAT §3.1) and cheap to commit as full hex.
const CHUNK_SIZE_LOG2: u8 = 10;
/// 2560 B ⇒ 3 chunks: 1024 / 1024 / 512 (a full, a full, and a short final chunk).
const PLAINTEXT_LEN: usize = 2560;
/// Expected chunk count for the fixture geometry above.
const CHUNK_COUNT: u64 = 3;

/// Fixed file DEK: bytes 0x00..0x1F (same value as `tests/vectors.rs`).
fn dek_a() -> [u8; 32] {
    let mut d = [0u8; 32];
    for (i, b) in d.iter_mut().enumerate() {
        *b = i as u8;
    }
    d
}

/// Fixed stream nonce prefix: bytes 0x20..0x2F (same value as `tests/vectors.rs`).
fn nonce_prefix_a() -> [u8; 16] {
    let mut n = [0u8; 16];
    for (i, b) in n.iter_mut().enumerate() {
        *b = 0x20 + i as u8;
    }
    n
}

/// Deterministic plaintext shared by every framing vector: `byte[i] = i mod 256`.
fn pattern(len: usize) -> Vec<u8> {
    (0..len).map(|i| (i % 256) as u8).collect()
}

fn sha256_hex(bytes: &[u8]) -> String {
    let mut h = Sha256::new();
    h.update(bytes);
    hex::encode(h.finalize())
}

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("vectors")
        .join("ncf3-multichunk.json")
}

/// Encrypts the fixture stream deterministically (vectors-only fixed nonce prefix).
fn fixture_stream() -> Vec<u8> {
    let dek = dek_a();
    let pt = pattern(PLAINTEXT_LEN);
    let mut enc =
        StreamEncryptor::with_fixed(&dek, pt.len() as u64, nonce_prefix_a(), CHUNK_SIZE_LOG2);
    let mut stream = Vec::new();
    stream.extend_from_slice(enc.header());
    stream.extend_from_slice(&enc.push(&pt).unwrap());
    stream.extend_from_slice(&enc.finish().unwrap());
    stream
}

/// Builds the exact committed JSON document (pretty-printed + trailing newline, keys in
/// serde_json's deterministic BTreeMap order — the same shape `ncf3.json` uses).
fn build_fixture_json() -> String {
    let stream = fixture_stream();
    let root = json!({
        "format": "NCF-3",
        "note": "Supplementary multi-chunk conformance fixture (generated by \
                 tests/vectors_multichunk.rs). 1 KiB chunks are DECODER-legal per \
                 CRYPTO-FORMAT §3.1; full bytes are committed so the JS harnesses can \
                 exercise multi-chunk sequential and random-access decryption. \
                 ncf3.json remains the frozen canonical artifact. Framing plaintext is \
                 byte[i] = i mod 256. Deterministic DEK/nonce values are vector-only; \
                 production never accepts caller nonces.",
        "framing": [{
            "label": "three_chunk_2560B",
            "plaintext_len": PLAINTEXT_LEN,
            "dek_hex": hex::encode(dek_a()),
            "nonce_prefix_hex": hex::encode(nonce_prefix_a()),
            "chunk_size_log2": CHUNK_SIZE_LOG2,
            "plaintext_pattern": "byte[i]=i%256",
            "stream_len": stream.len(),
            "stream_sha256": sha256_hex(&stream),
            "stream_hex": hex::encode(&stream),
        }],
    });
    serde_json::to_string_pretty(&root).unwrap() + "\n"
}

// =====================================================================================
// GENERATION
// =====================================================================================

#[test]
#[ignore = "run explicitly to (re)generate tests/vectors/ncf3-multichunk.json"]
fn gen_multichunk_fixture() {
    let json = build_fixture_json();
    let path = fixture_path();
    std::fs::create_dir_all(path.parent().unwrap()).unwrap();
    std::fs::write(&path, &json).unwrap();
    eprintln!("wrote {}", path.display());
}

// =====================================================================================
// VERIFICATION (default run)
// =====================================================================================

/// Reproducibility guard: the committed fixture must equal a fresh deterministic build,
/// byte for byte. Any drift in the engine or the generator fails here.
#[test]
fn multichunk_fixture_reproducible() {
    let committed = std::fs::read_to_string(fixture_path())
        .expect("tests/vectors/ncf3-multichunk.json missing — run gen_multichunk_fixture first");
    assert_eq!(
        build_fixture_json(),
        committed,
        "committed multi-chunk fixture is not reproducible from the deterministic generator"
    );
}

/// The committed bytes must decrypt correctly: sequentially (full anti-tamper checks) and
/// per chunk via random access, with the geometry the harnesses rely on.
#[test]
fn multichunk_fixture_decrypts() {
    let doc: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(fixture_path()).expect("fixture missing — run gen first"),
    )
    .unwrap();
    let v = &doc["framing"][0];
    let dek: [u8; 32] = hex::decode(v["dek_hex"].as_str().unwrap())
        .unwrap()
        .try_into()
        .unwrap();
    let stream = hex::decode(v["stream_hex"].as_str().unwrap()).unwrap();
    assert_eq!(stream.len() as u64, v["stream_len"].as_u64().unwrap());
    assert_eq!(sha256_hex(&stream), v["stream_sha256"].as_str().unwrap());

    let expected = pattern(PLAINTEXT_LEN);

    // Sequential decrypt (runs every end-of-stream invariant).
    let out = StreamDecryptor::decrypt_all(&dek, &stream).unwrap();
    assert_eq!(out, expected, "sequential roundtrip");

    // Random access: every chunk decrypts to the right pattern slice.
    let header = Header::parse(&stream[..HEADER_LEN]).unwrap();
    assert_eq!(header.chunk_count(), CHUNK_COUNT);
    let chunk_size = header.chunk_size() as usize;
    for index in 0..CHUNK_COUNT {
        let off = header.chunk_offset(index).unwrap() as usize;
        let ct_len = header.chunk_ciphertext_len(index).unwrap();
        // The fixture is a whole file in one stream, so every ranged read is "part 0 of 1".
        let got = decrypt_chunk(
            &dek,
            &header,
            PartPlacement::whole_file(),
            index,
            &stream[off..off + ct_len],
        )
        .unwrap();
        let start = index as usize * chunk_size;
        assert_eq!(
            got,
            &expected[start..start + got.len()],
            "random-access chunk {}",
            index
        );
    }
}
